# Generated by Django 4.2.1 on 2023-05-26 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edusch_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='administrator',
        ),
        migrations.AddField(
            model_name='assignment',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='subjects',
            field=models.ManyToManyField(to='edusch_app.course'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
