# Generated by Django 4.2.1 on 2023-06-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edusch_app', '0002_alter_staff_subjects_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to='edusch_app.user'),
        ),
    ]
