# Generated by Django 4.2.1 on 2023-05-30 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edusch_app', '0002_remove_subject_instructors_remove_subject_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
