# Generated by Django 4.2.1 on 2023-06-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edusch_app', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to='edusch_app.user'),
        ),
    ]
