# Generated by Django 4.2.1 on 2023-06-02 16:51

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Model1 = apps.get_model("edusch_app", "School")
    Model2 = apps.get_model("edusch_app", "Course")
    Model3 = apps.get_model("edusch_app", "Assignment")
    Model4 = apps.get_model("edusch_app", "Announcement")
    Model5 = apps.get_model("edusch_app", "Grade")
    Model6 = apps.get_model("edusch_app", "Student")
    Model7 = apps.get_model("edusch_app", "Instructor")
    Model8 = apps.get_model("edusch_app", "Parent")
    Model9 = apps.get_model("edusch_app", "User")
    
    for row in Model1.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
        
    for row in Model2.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model3.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model4.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model5.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model6.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model7.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model8.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    for row in Model9.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):
    

    dependencies = [
        ('edusch_app', '0004_remove_announcement_id_remove_assignment_id_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
