# Generated by Django 4.2.3 on 2023-08-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eduschola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='tel',
            new_name='phone',
        ),
    ]
