# Generated by Django 4.2.6 on 2023-10-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eduschola', '0002_rename_tel_staff_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Eduschola.staff'),
        ),
    ]
