# Generated by Django 4.2.6 on 2023-10-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduschola', '0003_remove_school_contact_information_school_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='gradeScore',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='session',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='term',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
