# Generated by Django 4.2.6 on 2023-11-22 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Eduschola', '0004_remove_grade_course_remove_grade_gradescore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=10)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('courses', models.ManyToManyField(to='Eduschola.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eduschola.student')),
            ],
        ),
    ]
