# Generated by Django 4.2.6 on 2023-11-24 22:07

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eduschola', '0005_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='lga',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
